/**
 * C2PA provenance service.
 *
 * Signing produces a real, COSE-signed C2PA manifest embedded in the asset
 * bytes via c2pa-node. When no signer is configured the service still records
 * provenance metadata, but it labels that record `degraded` and never reports
 * it as verified — an unsigned record is a filing-cabinet entry, not evidence.
 */

import crypto from "crypto";
import { promises as fs } from "node:fs";
import { v4 as uuidv4 } from "uuid";
import { prisma, isPrismaAvailable } from "../db";
import {
  C2paUnavailableError,
  assetDigest,
  backendStatus,
  signAndEmbed,
  verifyAsset,
} from "../lib/c2paBackend";
import type { ResolvedSignatureInfo } from "../lib/c2paBackend";
import type {
  ManifestDefinition,
  ProvenanceMode,
  SignRequest,
  SignResponse,
  SignatureSummary,
  StoredManifestEntry,
  VerifyResponse,
} from "../models/c2paSchemas";

export const CLAIM_GENERATOR = "AnimaForge/1.0.0";

/** IPTC digital source type for content generated by a trained model. */
const TRAINED_ALGORITHMIC_MEDIA =
  "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia";

/* ------------------------------------------------------------------ */
/*  In-memory fallback store                                           */
/* ------------------------------------------------------------------ */

const manifestStore = new Map<string, StoredManifestEntry>();
const outputIndex = new Map<string, string>();
const digestIndex = new Map<string, string>();

export function clearStore(): void {
  manifestStore.clear();
  outputIndex.clear();
  digestIndex.clear();
}

function remember(entry: StoredManifestEntry): void {
  manifestStore.set(entry.job_id, entry);
  outputIndex.set(entry.output_id, entry.job_id);
  if (entry.signed_asset_sha256)
    digestIndex.set(entry.signed_asset_sha256, entry.job_id);
  if (entry.asset_sha256) digestIndex.set(entry.asset_sha256, entry.job_id);
}

/* ------------------------------------------------------------------ */
/*  Manifest construction                                              */
/* ------------------------------------------------------------------ */

/** One-way hash so a public manifest never carries a raw user id. */
export function hashUserId(userId: string): string {
  return crypto
    .createHash("sha256")
    .update(`animaforge:user:${userId}`)
    .digest("hex");
}

export function buildManifestDefinition(
  params: SignRequest,
  format: string,
): ManifestDefinition {
  const now = new Date().toISOString();
  return {
    claim_generator: CLAIM_GENERATOR,
    format,
    title: `AnimaForge generated asset — job ${params.job_id}`,
    assertions: [
      {
        label: "c2pa.actions",
        data: {
          actions: [
            {
              action: "c2pa.created",
              softwareAgent: CLAIM_GENERATOR,
              when: now,
              digitalSourceType: TRAINED_ALGORITHMIC_MEDIA,
            },
          ],
        },
      },
      {
        label: "stds.schema-org.CreativeWork",
        data: {
          "@context": "https://schema.org",
          "@type": "CreativeWork",
          creditText: "Generated with AnimaForge",
        },
      },
      {
        label: "com.animaforge.generation",
        data: {
          job_id: params.job_id,
          project_id: params.project_id,
          shot_id: params.shot_id,
          model_id: params.model_id,
          input_hash: params.input_hash,
          user_id_hash: hashUserId(params.user_id),
          consent_ids: params.consent_ids,
          output_url: params.output_url,
          watermark_id: params.watermark_id ?? null,
        },
      },
    ],
  };
}

function summariseSignature(
  info: ResolvedSignatureInfo | null,
): SignatureSummary | null {
  if (!info) return null;
  return {
    algorithm: info.alg ?? null,
    issuer: info.issuer ?? null,
    cert_serial_number: info.cert_serial_number ?? null,
    timestamp: info.time ?? null,
  };
}

/* ------------------------------------------------------------------ */
/*  Persistence                                                        */
/* ------------------------------------------------------------------ */

async function persist(entry: StoredManifestEntry): Promise<void> {
  try {
    if (!isPrismaAvailable()) {
      remember(entry);
      return;
    }
    await prisma!.c2PAManifest.create({
      data: {
        outputId: entry.output_id,
        jobId: entry.job_id,
        projectId: entry.project_id,
        userIdHash: entry.user_id_hash,
        assetUrl: entry.output_url,
        assetPath: entry.asset_path,
        assetSha256: entry.asset_sha256,
        signedAssetSha256: entry.signed_asset_sha256,
        format: entry.format,
        manifestLabel: entry.manifest_label,
        claimGenerator: entry.manifest.claim_generator,
        signatureAlg: entry.signature?.algorithm ?? null,
        certSerialNumber: entry.signature?.cert_serial_number ?? null,
        certIssuer: entry.signature?.issuer ?? null,
        timestampedAt: entry.signature?.timestamp
          ? new Date(entry.signature.timestamp)
          : null,
        embedded: entry.embedded,
        signed: entry.signed,
        mode: entry.mode,
        degradedReason: entry.degraded_reason,
        manifestJson: entry.manifest as unknown as object,
        createdAt: new Date(entry.created_at),
      },
    });
    // Mirror into memory too so reads stay fast and survive a DB blip.
    remember(entry);
  } catch {
    remember(entry);
  }
}

function rowToEntry(row: Record<string, any>): StoredManifestEntry {
  const manifest = (row.manifestJson ?? {}) as ManifestDefinition;
  const generation = manifest.assertions?.find(
    (a) => a.label === "com.animaforge.generation",
  )?.data as Record<string, unknown> | undefined;
  return {
    output_id: row.outputId,
    job_id: row.jobId,
    project_id: row.projectId ?? "",
    shot_id: (generation?.shot_id as string) ?? "",
    model_id: (generation?.model_id as string) ?? "",
    user_id_hash: row.userIdHash ?? "",
    consent_ids: (generation?.consent_ids as string[]) ?? [],
    output_url: row.assetUrl ?? "",
    mode: row.mode as ProvenanceMode,
    signed: row.signed,
    embedded: row.embedded,
    format: row.format,
    manifest,
    manifest_label: row.manifestLabel,
    signature:
      row.signatureAlg || row.certSerialNumber
        ? {
            algorithm: row.signatureAlg,
            issuer: row.certIssuer,
            cert_serial_number: row.certSerialNumber,
            timestamp: row.timestampedAt
              ? row.timestampedAt.toISOString()
              : null,
          }
        : null,
    asset_sha256: row.assetSha256,
    signed_asset_sha256: row.signedAssetSha256,
    asset_path: row.assetPath,
    degraded_reason: row.degradedReason,
    created_at: row.createdAt.toISOString(),
  };
}

async function findByOutputId(
  outputId: string,
): Promise<StoredManifestEntry | null> {
  try {
    if (isPrismaAvailable()) {
      const row = await prisma!.c2PAManifest.findUnique({
        where: { outputId },
      });
      if (row) return rowToEntry(row as Record<string, any>);
    }
  } catch {
    // fall through
  }
  const jobId = outputIndex.get(outputId);
  return jobId ? (manifestStore.get(jobId) ?? null) : null;
}

async function findByDigest(
  sha256: string,
): Promise<StoredManifestEntry | null> {
  try {
    if (isPrismaAvailable()) {
      const row = await prisma!.c2PAManifest.findFirst({
        where: { OR: [{ signedAssetSha256: sha256 }, { assetSha256: sha256 }] },
        orderBy: { createdAt: "desc" },
      });
      if (row) return rowToEntry(row as Record<string, any>);
    }
  } catch {
    // fall through
  }
  const jobId = digestIndex.get(sha256);
  return jobId ? (manifestStore.get(jobId) ?? null) : null;
}

export async function getManifestByJobId(
  jobId: string,
): Promise<StoredManifestEntry | null> {
  try {
    if (isPrismaAvailable()) {
      const row = await prisma!.c2PAManifest.findFirst({
        where: { jobId },
        orderBy: { createdAt: "desc" },
      });
      if (row) return rowToEntry(row as Record<string, any>);
    }
  } catch {
    // fall through
  }
  return manifestStore.get(jobId) ?? null;
}

/* ------------------------------------------------------------------ */
/*  Signing                                                            */
/* ------------------------------------------------------------------ */

function guessFormat(params: SignRequest): string {
  if (params.mime_type) return params.mime_type;
  const source = params.asset_path ?? params.output_url;
  const ext = source.split("?")[0].split(".").pop()?.toLowerCase() ?? "";
  const map: Record<string, string> = {
    png: "image/png",
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    webp: "image/webp",
    tif: "image/tiff",
    tiff: "image/tiff",
    mp4: "video/mp4",
    m4v: "video/mp4",
    mov: "video/quicktime",
    webm: "video/webm",
    wav: "audio/wav",
    mp3: "audio/mpeg",
  };
  return map[ext] ?? "application/octet-stream";
}

export async function createManifest(
  params: SignRequest,
): Promise<SignResponse> {
  const outputId = uuidv4();
  const format = guessFormat(params);
  const manifest = buildManifestDefinition(params, format);
  const createdAt = new Date().toISOString();
  const status = await backendStatus();

  const hasAsset = Boolean(params.asset_base64 || params.asset_path);
  const sourceBuffer = params.asset_base64
    ? Buffer.from(params.asset_base64, "base64")
    : null;

  const base: StoredManifestEntry = {
    output_id: outputId,
    job_id: params.job_id,
    project_id: params.project_id,
    shot_id: params.shot_id,
    model_id: params.model_id,
    user_id_hash: hashUserId(params.user_id),
    consent_ids: params.consent_ids,
    output_url: params.output_url,
    mode: "degraded",
    signed: false,
    embedded: false,
    format,
    manifest,
    manifest_label: null,
    signature: null,
    asset_sha256: sourceBuffer ? assetDigest(sourceBuffer) : null,
    signed_asset_sha256: null,
    asset_path: params.asset_path ?? null,
    degraded_reason: null,
    created_at: createdAt,
  };

  // --- Degraded: no usable signer -------------------------------------
  if (!status.canSign) {
    const entry: StoredManifestEntry = {
      ...base,
      mode: "degraded",
      degraded_reason: status.degradedReasons.join("; "),
    };
    await persist(entry);
    return {
      ...entry,
      manifest_url: `/governance/c2pa/manifest/${params.job_id}`,
      degraded: true,
      warning:
        "DEGRADED MODE: no C2PA manifest was signed or embedded. This record is " +
        "unsigned metadata and must not be presented as verified provenance. " +
        "Configure C2PA_SIGNING_CERT and C2PA_PRIVATE_KEY to enable real signing.",
    };
  }

  // --- Signer available but nothing to sign ---------------------------
  if (!hasAsset) {
    const entry: StoredManifestEntry = {
      ...base,
      mode: "unsigned-record",
      degraded_reason:
        "no asset bytes supplied; a manifest can only be embedded into an actual asset",
    };
    await persist(entry);
    return {
      ...entry,
      manifest_url: `/governance/c2pa/manifest/${params.job_id}`,
      degraded: true,
      warning:
        "A signer is configured but no asset was supplied, so nothing was signed " +
        "or embedded. Send asset_base64 or asset_path to produce a real manifest.",
    };
  }

  // --- Real signing ----------------------------------------------------
  try {
    const result = await signAndEmbed(
      {
        buffer: sourceBuffer ?? undefined,
        path: params.asset_path,
        mimeType: format,
        outputPath: params.output_path,
      },
      manifest as unknown as Record<string, unknown>,
    );

    const signedBytes =
      result.buffer ?? (result.path ? await fs.readFile(result.path) : null);

    const entry: StoredManifestEntry = {
      ...base,
      mode: "c2pa-embedded",
      signed: true,
      embedded: true,
      manifest_label: result.manifestLabel,
      signature: summariseSignature(result.signatureInfo),
      signed_asset_sha256: signedBytes ? assetDigest(signedBytes) : null,
      asset_path: result.path ?? params.asset_path ?? null,
    };
    await persist(entry);

    const response: SignResponse = {
      ...entry,
      manifest_url: `/governance/c2pa/manifest/${params.job_id}`,
      degraded: false,
    };
    if (result.path) {
      response.output_path = result.path;
    } else if (result.buffer) {
      response.asset_base64 = result.buffer.toString("base64");
    }
    return response;
  } catch (err) {
    const reason =
      err instanceof C2paUnavailableError
        ? err.reasons.join("; ")
        : err instanceof Error
          ? err.message
          : String(err);
    const entry: StoredManifestEntry = {
      ...base,
      mode: "degraded",
      degraded_reason: `signing failed: ${reason}`,
    };
    await persist(entry);
    return {
      ...entry,
      manifest_url: `/governance/c2pa/manifest/${params.job_id}`,
      degraded: true,
      warning:
        `DEGRADED MODE: signing was attempted but failed (${reason}). ` +
        "The stored record is unsigned metadata only.",
    };
  }
}

/* ------------------------------------------------------------------ */
/*  Verification                                                       */
/* ------------------------------------------------------------------ */

function entryToResponse(
  entry: StoredManifestEntry | null,
  over: Partial<VerifyResponse>,
): VerifyResponse {
  return {
    status: "unverified",
    cryptographically_verified: false,
    valid: false,
    record_found: entry !== null,
    reason: null,
    manifest: entry?.manifest ?? null,
    manifest_label: entry?.manifest_label ?? null,
    signature: entry?.signature ?? null,
    generator: entry?.manifest.claim_generator ?? null,
    created_at: entry?.created_at ?? null,
    model_id: entry?.model_id ?? null,
    mode: entry?.mode ?? null,
    validation_status: [],
    ...over,
  };
}

/**
 * Verify by output id.
 *
 * If the record points at an asset we can still read, the manifest is checked
 * cryptographically. Otherwise the honest answer is "unverified" — we know a
 * record exists, which is not the same as knowing the file is authentic.
 */
export async function verifyManifest(
  outputId: string,
): Promise<VerifyResponse> {
  const entry = await findByOutputId(outputId);
  if (!entry) {
    return entryToResponse(null, {
      status: "not_found",
      reason: "no provenance record exists for this output id",
    });
  }

  if (entry.asset_path) {
    try {
      await fs.access(entry.asset_path);
      const result = await verifyAsset({
        path: entry.asset_path,
        mimeType: entry.format,
      });
      return entryToResponse(entry, {
        status: result.status,
        cryptographically_verified: result.cryptographicallyVerified,
        valid: result.status === "valid",
        reason: result.reason,
        manifest_label: result.manifestLabel ?? entry.manifest_label,
        signature: summariseSignature(result.signatureInfo) ?? entry.signature,
        validation_status: result.validationStatus,
      });
    } catch {
      // Asset is gone or unreadable — fall through to the record-only answer.
    }
  }

  return entryToResponse(entry, {
    status: "unverified",
    reason:
      entry.mode === "c2pa-embedded"
        ? "a signed manifest was embedded at generation time, but the asset was not " +
          "available to re-check here; POST the asset to /governance/c2pa/verify to validate it"
        : `this record is ${entry.mode} and carries no cryptographic signature` +
          (entry.degraded_reason ? ` (${entry.degraded_reason})` : ""),
  });
}

/** Verify an asset the caller supplies — the only path that can return "valid". */
export async function verifySuppliedAsset(input: {
  asset_base64?: string;
  asset_path?: string;
  mime_type?: string;
}): Promise<VerifyResponse> {
  const buffer = input.asset_base64
    ? Buffer.from(input.asset_base64, "base64")
    : null;
  const mimeType = input.mime_type ?? "application/octet-stream";

  const result = await verifyAsset({
    buffer: buffer ?? undefined,
    path: input.asset_path,
    mimeType,
  });

  let entry: StoredManifestEntry | null = null;
  if (buffer) entry = await findByDigest(assetDigest(buffer));
  if (!entry && input.asset_path) {
    try {
      entry = await findByDigest(
        assetDigest(await fs.readFile(input.asset_path)),
      );
    } catch {
      // no record match
    }
  }

  return entryToResponse(entry, {
    status: result.status,
    cryptographically_verified: result.cryptographicallyVerified,
    valid: result.status === "valid",
    reason: result.reason,
    manifest_label: result.manifestLabel ?? entry?.manifest_label ?? null,
    signature:
      summariseSignature(result.signatureInfo) ?? entry?.signature ?? null,
    validation_status: result.validationStatus,
  });
}

/* ------------------------------------------------------------------ */
/*  Capabilities                                                       */
/* ------------------------------------------------------------------ */

export interface C2paCapabilities {
  service: string;
  signing: {
    available: boolean;
    library: string;
    library_available: boolean;
    library_error: string | null;
    credentials_present: boolean;
    credentials_error: string | null;
    algorithm: string;
    timestamp_authority: string;
  };
  verification: { available: boolean };
  database: { connected: boolean };
  degraded: boolean;
  degraded_reasons: string[];
}

export async function getCapabilities(): Promise<C2paCapabilities> {
  const status = await backendStatus();
  const reasons = [...status.degradedReasons];
  if (!isPrismaAvailable()) {
    reasons.push(
      "no database connection — provenance records are in-memory only",
    );
  }
  return {
    service: "c2pa-signing",
    signing: {
      available: status.canSign,
      library: "c2pa-node",
      library_available: status.libraryAvailable,
      library_error: status.libraryError,
      credentials_present: status.credentialsPresent,
      credentials_error: status.credentialsError,
      algorithm: status.algorithm,
      timestamp_authority: status.tsaUrl,
    },
    verification: { available: status.canVerify },
    database: { connected: isPrismaAvailable() },
    degraded: reasons.length > 0,
    degraded_reasons: reasons,
  };
}
