/**
 * WebRTC signalling protocol.
 *
 * Signalling is the part WebRTC deliberately leaves undefined: peers cannot
 * discover each other or exchange SDP and ICE candidates without an out-of-band
 * channel. This is that channel — a small typed protocol over the existing
 * WebSocket server.
 *
 * The server never touches media. It brokers the handshake and then the audio
 * and video flow peer-to-peer (or via TURN). That is the whole point: relaying
 * frames through Node would put a CPU-bound transcode in the hot path of every
 * viewer.
 */

import { z } from 'zod';

/** A broadcaster publishes media; a viewer subscribes to it. */
export const peerRoleSchema = z.enum(['broadcaster', 'viewer']);
export type PeerRole = z.infer<typeof peerRoleSchema>;

/**
 * SDP is opaque to us — it is generated by the browser's RTCPeerConnection and
 * consumed by another one. Validating its contents here would mean maintaining
 * a parser for a format we do not own, so it is checked for shape and size
 * only. The size cap matters: SDP with many ICE candidates is a few KB, and
 * anything far larger is either a bug or an attempt to use the relay as free
 * message storage.
 */
const MAX_SDP_BYTES = 64 * 1024;
const MAX_CANDIDATE_BYTES = 4 * 1024;

export const sessionDescriptionSchema = z.object({
  type: z.enum(['offer', 'answer', 'pranswer', 'rollback']),
  sdp: z.string().max(MAX_SDP_BYTES),
});

export const iceCandidateSchema = z.object({
  candidate: z.string().max(MAX_CANDIDATE_BYTES),
  sdpMid: z.string().nullable().optional(),
  sdpMLineIndex: z.number().int().nullable().optional(),
  usernameFragment: z.string().nullable().optional(),
});

/* -- client -> server ------------------------------------------------------ */

export const joinMessageSchema = z.object({
  type: z.literal('join'),
  sessionId: z.string().min(1),
  role: peerRoleSchema,
  /** Optional display name, surfaced to other peers. */
  displayName: z.string().max(120).optional(),
});

export const leaveMessageSchema = z.object({
  type: z.literal('leave'),
});

export const offerMessageSchema = z.object({
  type: z.literal('offer'),
  to: z.string().min(1),
  description: sessionDescriptionSchema,
});

export const answerMessageSchema = z.object({
  type: z.literal('answer'),
  to: z.string().min(1),
  description: sessionDescriptionSchema,
});

export const iceMessageSchema = z.object({
  type: z.literal('ice-candidate'),
  to: z.string().min(1),
  candidate: iceCandidateSchema,
});

export const clientMessageSchema = z.discriminatedUnion('type', [
  joinMessageSchema,
  leaveMessageSchema,
  offerMessageSchema,
  answerMessageSchema,
  iceMessageSchema,
]);

export type ClientMessage = z.infer<typeof clientMessageSchema>;

/* -- server -> client ------------------------------------------------------ */

export interface PeerInfo {
  peerId: string;
  role: PeerRole;
  displayName?: string;
}

export interface IceServerConfig {
  urls: string[];
  username?: string;
  credential?: string;
}

export type ServerMessage =
  | {
      type: 'joined';
      peerId: string;
      sessionId: string;
      /** Peers already in the session. The joiner offers to each of them. */
      peers: PeerInfo[];
      iceServers: IceServerConfig[];
      /**
       * Whether a TURN relay is configured. Without one, peers behind
       * symmetric NAT cannot connect at all — the client is told rather than
       * left to fail with an opaque ICE timeout.
       */
      turnConfigured: boolean;
      warnings: string[];
    }
  | { type: 'peer-joined'; peer: PeerInfo }
  | { type: 'peer-left'; peerId: string }
  | { type: 'offer'; from: string; description: z.infer<typeof sessionDescriptionSchema> }
  | { type: 'answer'; from: string; description: z.infer<typeof sessionDescriptionSchema> }
  | { type: 'ice-candidate'; from: string; candidate: z.infer<typeof iceCandidateSchema> }
  | { type: 'error'; code: SignalingErrorCode; message: string };

export type SignalingErrorCode =
  | 'invalid_message'
  | 'not_joined'
  | 'already_joined'
  | 'unknown_peer'
  | 'session_full'
  | 'peer_not_in_session';

export interface ParseResult {
  ok: boolean;
  message?: ClientMessage;
  error?: string;
}

/** Parse a raw frame. Never throws — a bad frame is a client error, not ours. */
export function parseClientMessage(raw: string): ParseResult {
  let json: unknown;
  try {
    json = JSON.parse(raw);
  } catch {
    return { ok: false, error: 'not valid JSON' };
  }

  const parsed = clientMessageSchema.safeParse(json);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? 'invalid message' };
  }
  return { ok: true, message: parsed.data };
}
