"""Service layer for avatar reconstruction (X5 7-step pipeline).

This module orchestrates the four X5 subsystems and writes their outputs to
storage.  It keeps the original public interface — :data:`X5_PIPELINE_STEPS`
and :func:`create_avatar_job` — but the implementation behind it is real:

* Subsystem 1 (:mod:`.avatar.reconstruction`) produces an actual Gaussian
  splat cloud and triangle mesh, exported as a real binary PLY and a real GLB.
* Subsystem 2 (:mod:`.avatar.sss`) computes skin scattering from tissue optics.
* Subsystem 3 (:mod:`.avatar.facs`) solves FACS action units into blendshapes.
* Subsystem 4 (:mod:`.avatar.eyes`) simulates a sampled eye animation curve.

Three rules hold everywhere in this file:

1. A step is only reported ``completed`` if it ran.  Steps that cannot run say
   ``skipped`` and carry the reason.
2. Every URL in the result refers to bytes that were written to storage.
3. When the procedural engine is used, ``engine="mock"`` and ``is_mock=True``
   appear in the response, and ``mock_notice`` explains what that means.
"""

from __future__ import annotations

import json
import time
import uuid
from typing import Any

import numpy as np

from .avatar import engine as engine_mod
from .avatar import eyes as eyes_mod
from .avatar import facs as facs_mod
from .avatar import gltf as gltf_mod
from .avatar import reconstruction as recon_mod
from .avatar import sss as sss_mod
from .avatar import storage as storage_mod

# The seven stages of the X5 avatar reconstruction pipeline.
X5_PIPELINE_STEPS: list[dict[str, str]] = [
    {"name": "multi_view_alignment", "description": "Align multi-view photo inputs"},
    {"name": "volumetric_reconstruction", "description": "Build volumetric representation from aligned views"},
    {"name": "mesh_extraction", "description": "Extract polygon mesh from volume"},
    {"name": "texture_baking", "description": "Bake high-resolution textures onto mesh UV map"},
    {"name": "flame_fitting", "description": "Fit FLAME parametric head model for expression control"},
    {"name": "body_estimation", "description": "Estimate body pose and proportions"},
    {"name": "quality_validation", "description": "Validate identity preservation (threshold > 0.92)"},
]

STATUS_COMPLETED = "completed"
STATUS_SKIPPED = "skipped"
STATUS_FAILED = "failed"

IDENTITY_THRESHOLD = 0.92

MOCK_NOTICE = (
    "Generated by the procedural CPU engine (AVATAR_ENGINE=mock). The mesh and "
    "splat cloud are real, exportable artifacts, but they are synthesised from "
    "the character identifier — the reference photographs were not analysed. "
    "Set AVATAR_ENGINE=real on a CUDA host with nerfstudio installed for "
    "photograph-driven reconstruction."
)


def create_avatar_job(
    character_id: str,
    photos: list[str],
    style_mode: str = "realistic",
    *,
    skin_tone: str | None = None,
    eye_clip_seconds: float = 10.0,
) -> dict[str, Any]:
    """Run the X5 7-step avatar reconstruction pipeline.

    Args:
        character_id: Identifier the artifacts are filed under.
        photos: Reference photo URLs or paths; at least one is required.
        style_mode: Downstream render style; recorded on the artifacts.
        skin_tone: Optional ``#RRGGBB`` swatch driving subsurface scattering.
        eye_clip_seconds: Length of the generated eye animation clip.

    Returns:
        A job record. ``steps_completed`` reports each stage's true status,
        and ``artifacts`` lists only files that were actually written.

    Raises:
        ValueError: if ``photos`` is empty or ``skin_tone`` is malformed.
        EngineUnavailable: if ``AVATAR_ENGINE=real`` cannot run on this host.
    """
    if not photos:
        raise ValueError("At least one reference photo is required")

    job_id = str(uuid.uuid4())
    capability = engine_mod.probe()
    active_engine = engine_mod.resolve_engine()
    is_mock = active_engine == engine_mod.ENGINE_MOCK

    steps: list[dict[str, Any]] = []
    warnings: list[str] = []
    recorder = _StepRecorder(steps)

    # ── Steps 1-3: alignment, volumetric reconstruction, mesh extraction ──
    with recorder.step(1) as step:
        if len(photos) < 2:
            step.skip(
                "A single reference view provides no multi-view constraint; "
                "no bundle adjustment was performed."
            )
        else:
            step.complete(metrics={"view_count": len(photos)})

    started = time.perf_counter()
    result = recon_mod.reconstruct(character_id, photos, engine=active_engine)
    reconstruction_ms = (time.perf_counter() - started) * 1000.0

    with recorder.step(2) as step:
        step.complete(
            duration_ms=reconstruction_ms,
            metrics={
                "engine": result.engine,
                "splat_count": result.splats.count,
                "reprojection_rms_px": _finite_or_none(result.alignment_rms),
            },
        )

    with recorder.step(3) as step:
        step.complete(
            metrics={
                "vertex_count": int(result.positions.shape[0]),
                "triangle_count": int(result.indices.shape[0]),
            }
        )

    # ── Step 4: texture baking ────────────────────────────────────────────
    with recorder.step(4) as step:
        step.complete(
            metrics={
                "uv_channels": 1,
                "vertex_colors": int(result.vertex_colors.shape[0]),
            },
            note=(
                "Per-vertex albedo and spherical UVs were baked. No raster "
                "texture atlas is written; the GLB carries vertex colour data "
                "only."
            ),
        )

    # ── Step 5: FLAME fitting ─────────────────────────────────────────────
    with recorder.step(5) as step:
        step.skip(
            "FLAME requires a separately licensed model file (see "
            "AVATAR_FLAME_MODEL_PATH in docs/avatar-studio.md). A generic SVD "
            "shape basis was fitted instead — this is not a FLAME fit.",
            metrics={
                "substitute_model": "svd-shape-basis",
                "relative_residual": round(result.shape_basis_residual, 6),
            },
        )
    warnings.append("flame_fitting was skipped: no licensed FLAME model available.")

    # ── Step 6: body estimation ───────────────────────────────────────────
    with recorder.step(6) as step:
        step.complete(
            metrics=result.body_proportions,
            note=(
                "Proportions are scaled from the reconstructed head using the "
                "canonical 7.5-head figure. No body geometry was reconstructed."
            ),
        )

    # ── Subsystems 2-4 ────────────────────────────────────────────────────
    skin_profile = (
        sss_mod.profile_for_skin_tone(skin_tone)
        if skin_tone
        else sss_mod.compute_skin_profile()
    )
    facs_rig = facs_mod.build_facs_rig(character_id, active_engine)
    eye_animation = eyes_mod.simulate_eyes(
        duration_s=eye_clip_seconds,
        seed=_seed_for(character_id),
    )

    # ── Artifacts ─────────────────────────────────────────────────────────
    artifacts = _write_artifacts(
        character_id=character_id,
        job_id=job_id,
        style_mode=style_mode,
        engine=active_engine,
        result=result,
        skin_profile=skin_profile,
        facs_rig=facs_rig,
        eye_animation=eye_animation,
    )

    # ── Step 7: quality validation ────────────────────────────────────────
    geometry_metrics = _validate_geometry(result)
    with recorder.step(7) as step:
        step.skip(
            "Identity preservation scoring requires a face-recognition model "
            "(AVATAR_IDENTITY_MODEL_PATH); none is configured, so no identity "
            f"score was computed against the {IDENTITY_THRESHOLD} threshold. "
            "Geometric self-consistency checks ran instead.",
            metrics={
                "identity_score": None,
                "identity_threshold": IDENTITY_THRESHOLD,
                "identity_check_ran": False,
                **geometry_metrics,
            },
        )
    warnings.append(
        "quality_validation did not verify identity preservation: no "
        "face-recognition model is configured."
    )

    if is_mock:
        warnings.insert(0, MOCK_NOTICE)

    return {
        "job_id": job_id,
        "character_id": character_id,
        "style_mode": style_mode,
        "engine": active_engine,
        "requested_engine": capability.requested_engine,
        "is_mock": is_mock,
        "mock_notice": MOCK_NOTICE if is_mock else None,
        "steps_completed": steps,
        "steps_summary": _summarise(steps),
        "artifacts": {name: handle.as_dict() for name, handle in artifacts.items()},
        "model_url": artifacts["gltf"].url,
        "rig_url": artifacts["facs_rig"].url,
        "splat_url": artifacts["splats"].url,
        "eye_animation_url": artifacts["eye_animation"].url,
        "skin": skin_profile.as_dict(),
        "body_params": result.body_proportions,
        "eye_statistics": eye_animation.as_dict()["statistics"],
        "capability": capability.as_dict(),
        "warnings": warnings,
    }


def pipeline_capability() -> dict[str, Any]:
    """Report what the avatar pipeline can actually do on this host."""
    capability = engine_mod.probe()
    return {
        **capability.as_dict(),
        "storage_backend": storage_mod.storage_backend(),
        "storage_root": str(storage_mod.storage_root()),
        "identity_scoring_available": False,
        "flame_fitting_available": False,
        "subsystems": {
            "reconstruction": capability.active_engine,
            "subsurface_scattering": "cpu",
            "facs": "cpu",
            "eye_system": "cpu",
        },
        "mock_notice": (
            MOCK_NOTICE
            if capability.active_engine == engine_mod.ENGINE_MOCK
            else None
        ),
    }


# ── Artifact writing ─────────────────────────────────────────────────────────


def _write_artifacts(
    *,
    character_id: str,
    job_id: str,
    style_mode: str,
    engine: str,
    result: recon_mod.ReconstructionResult,
    skin_profile: sss_mod.SkinScatteringProfile,
    facs_rig: dict[str, Any],
    eye_animation: eyes_mod.EyeAnimation,
) -> dict[str, storage_mod.StoredArtifact]:
    prefix = f"{character_id}/{job_id}"

    mesh = gltf_mod.Mesh(
        positions=result.positions,
        indices=result.indices,
        morph_targets=_expression_morph_targets(result.positions),
    )
    glb = gltf_mod.write_glb(
        mesh,
        asset_name=f"{character_id}-avatar",
        generator=f"AnimaForge X5 ({engine} engine, style={style_mode})",
    )
    ply = recon_mod.write_splat_ply(result.splats)

    return {
        "gltf": storage_mod.store_artifact(
            f"{prefix}/avatar.glb", glb, "model/gltf-binary"
        ),
        "splats": storage_mod.store_artifact(
            f"{prefix}/splats.ply", ply, "application/octet-stream"
        ),
        "facs_rig": storage_mod.store_artifact(
            f"{prefix}/facs_rig.json",
            _dump_json(facs_rig),
            "application/json",
        ),
        "eye_animation": storage_mod.store_artifact(
            f"{prefix}/eye_animation.json",
            _dump_json(eye_animation.as_dict()),
            "application/json",
        ),
        "skin_profile": storage_mod.store_artifact(
            f"{prefix}/skin_profile.json",
            _dump_json(skin_profile.as_dict()),
            "application/json",
        ),
    }


def _expression_morph_targets(positions: np.ndarray) -> list[gltf_mod.MorphTarget]:
    """Build morph targets so the exported GLB carries drivable blendshapes.

    Deltas are analytic displacements of the regions each expression moves,
    keyed by the same names the FACS solver emits, so a runtime can drive them
    directly from :func:`.facs.solve_blendshapes` output.
    """
    y = positions[:, 1]
    z = positions[:, 2]
    span = float(np.ptp(y)) or 1.0
    # Normalised height: 0 at the chin, 1 at the crown.
    height = (y - y.min()) / span
    front = np.clip(z / (np.abs(z).max() or 1.0), 0.0, 1.0)

    def _target(name: str, mask: np.ndarray, direction: np.ndarray) -> gltf_mod.MorphTarget:
        deltas = (mask[:, None] * direction[None, :]).astype(np.float32)
        return gltf_mod.MorphTarget(name=name, position_deltas=deltas)

    jaw_mask = np.clip(1.0 - height / 0.35, 0.0, 1.0) * front
    brow_mask = np.exp(-(((height - 0.72) / 0.06) ** 2)) * front
    smile_mask = np.exp(-(((height - 0.30) / 0.07) ** 2)) * front
    lid_mask = np.exp(-(((height - 0.62) / 0.04) ** 2)) * front

    scale = span * 0.06
    return [
        _target("jawOpen", jaw_mask, np.array([0.0, -scale, 0.0])),
        _target("browInnerUp", brow_mask, np.array([0.0, scale * 0.4, 0.0])),
        _target("mouthSmileLeft", smile_mask, np.array([scale * 0.3, scale * 0.25, 0.0])),
        _target("mouthSmileRight", smile_mask, np.array([-scale * 0.3, scale * 0.25, 0.0])),
        _target("eyeBlinkLeft", lid_mask, np.array([0.0, -scale * 0.3, 0.0])),
        _target("eyeBlinkRight", lid_mask, np.array([0.0, -scale * 0.3, 0.0])),
    ]


def _validate_geometry(result: recon_mod.ReconstructionResult) -> dict[str, Any]:
    """Geometric self-consistency checks — not an identity check."""
    positions = result.positions
    indices = result.indices

    edges = np.concatenate(
        [indices[:, [0, 1]], indices[:, [1, 2]], indices[:, [2, 0]]], axis=0
    )
    undirected = np.sort(edges, axis=1)
    _, counts = np.unique(undirected, axis=0, return_counts=True)

    # Zero-area triangles, not merely repeated indices: distinct vertices can
    # still be coincident, which a repeated-index test would miss entirely.
    tri = positions[indices]
    areas = 0.5 * np.linalg.norm(
        np.cross(tri[:, 1] - tri[:, 0], tri[:, 2] - tri[:, 0]), axis=1
    )

    return {
        "geometry_checks_ran": True,
        "vertices_finite": bool(np.isfinite(positions).all()),
        "indices_in_range": bool(int(indices.max()) < positions.shape[0]),
        "degenerate_triangles": int(np.sum(areas <= 1e-12)),
        "min_triangle_area_m2": float(areas.min()),
        "non_manifold_edges": int(np.sum(counts > 2)),
        "boundary_edges": int(np.sum(counts == 1)),
        "closed_manifold": bool(np.all(counts == 2)),
        "splat_opacity_finite": bool(np.isfinite(result.splats.opacities).all()),
    }


def _summarise(steps: list[dict[str, Any]]) -> dict[str, int]:
    summary = {STATUS_COMPLETED: 0, STATUS_SKIPPED: 0, STATUS_FAILED: 0}
    for step in steps:
        summary[step["status"]] = summary.get(step["status"], 0) + 1
    return summary


def _dump_json(payload: dict[str, Any]) -> bytes:
    return json.dumps(payload, indent=2, sort_keys=False).encode("utf-8")


def _finite_or_none(value: float) -> float | None:
    return None if not np.isfinite(value) else float(value)


def _seed_for(character_id: str) -> int:
    return int.from_bytes(character_id.encode("utf-8")[:8].ljust(8, b"\0"), "big") % (
        2**32
    )


# ── Step recording ───────────────────────────────────────────────────────────


class _Step:
    """Records the true outcome of one pipeline stage."""

    def __init__(self, index: int) -> None:
        definition = X5_PIPELINE_STEPS[index - 1]
        self.record: dict[str, Any] = {
            "step": index,
            "name": definition["name"],
            "description": definition["description"],
            "status": STATUS_FAILED,
            "note": None,
        }
        self._started = time.perf_counter()

    def complete(
        self,
        *,
        metrics: dict[str, Any] | None = None,
        note: str | None = None,
        duration_ms: float | None = None,
    ) -> None:
        self.record["status"] = STATUS_COMPLETED
        self._finish(metrics, note, duration_ms)

    def skip(
        self,
        reason: str,
        *,
        metrics: dict[str, Any] | None = None,
    ) -> None:
        self.record["status"] = STATUS_SKIPPED
        self.record["reason"] = reason
        self._finish(metrics, None, None)

    def fail(self, reason: str) -> None:
        self.record["status"] = STATUS_FAILED
        self.record["reason"] = reason
        self._finish(None, None, None)

    def _finish(
        self,
        metrics: dict[str, Any] | None,
        note: str | None,
        duration_ms: float | None,
    ) -> None:
        elapsed = (time.perf_counter() - self._started) * 1000.0
        self.record["duration_ms"] = round(
            duration_ms if duration_ms is not None else elapsed, 3
        )
        if metrics is not None:
            self.record["metrics"] = metrics
        if note is not None:
            self.record["note"] = note


class _StepRecorder:
    """Appends step records, marking a stage failed if it raises."""

    def __init__(self, sink: list[dict[str, Any]]) -> None:
        self._sink = sink

    def step(self, index: int) -> _StepContext:
        return _StepContext(_Step(index), self._sink)


class _StepContext:
    def __init__(self, step: _Step, sink: list[dict[str, Any]]) -> None:
        self._step = step
        self._sink = sink

    def __enter__(self) -> _Step:
        return self._step

    def __exit__(self, exc_type, exc, traceback) -> bool:
        if exc is not None:
            self._step.fail(f"{exc_type.__name__}: {exc}")
        self._sink.append(self._step.record)
        return False
