-- Baseline. Replaces the four migrations that preceded it.
--
-- Those encoded a different datamodel than schema.prisma: 75 columns to
-- add, 103 to drop, 63 to retype and 19 foreign keys to lose across 19
-- tables (#68). Reconciling forward would have meant a migration that
-- deletes columns, because `migrate diff` cannot tell a rename from a
-- drop-and-add. Nothing had ever run `migrate deploy` -- not CI, not
-- either deploy workflow, not k8s, not docker -- so no database held data
-- under the old history and regenerating it cost nothing.
--
-- Generated by `prisma migrate diff --from-empty --to-schema-datamodel`
-- and verified by .github/workflows/schema-drift.yml.

-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "email" TEXT NOT NULL,
    "display_name" TEXT,
    "avatar_url" TEXT,
    "org_id" UUID,
    "role" TEXT NOT NULL DEFAULT 'creator',
    "tier" TEXT NOT NULL DEFAULT 'free',
    "gen_memory" JSONB NOT NULL DEFAULT '{}',
    "style_prefs" JSONB NOT NULL DEFAULT '{}',
    "consent_flags" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "onboarding_complete" BOOLEAN NOT NULL DEFAULT false,
    "referral_code" TEXT,
    "referred_by" TEXT,
    "referral_credits" INTEGER NOT NULL DEFAULT 0,
    "triggered_milestones" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "cookie_consent" JSONB NOT NULL DEFAULT '{}',
    "welcome_email_sent" BOOLEAN NOT NULL DEFAULT false,
    "push_token" TEXT,
    "deleted_at" TIMESTAMPTZ,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "organizations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "logo_url" TEXT,
    "settings" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "deleted_at" TIMESTAMPTZ,

    CONSTRAINT "organizations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teams" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "teams_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "memberships" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "team_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'member',

    CONSTRAINT "memberships_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "api_keys" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "key_hash" TEXT NOT NULL,
    "scopes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "expires_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "api_keys_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "projects" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "owner_id" UUID NOT NULL,
    "org_id" UUID,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "world_bible" JSONB NOT NULL DEFAULT '{}',
    "brand_kit" JSONB NOT NULL DEFAULT '{}',
    "style_lock" JSONB NOT NULL DEFAULT '{}',
    "status" TEXT NOT NULL DEFAULT 'active',
    "phase" TEXT NOT NULL DEFAULT 'pre_production',
    "model_version" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "review_token" TEXT,
    "review_token_expires_at" TIMESTAMPTZ,
    "deleted_at" TIMESTAMPTZ,

    CONSTRAINT "projects_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "scenes" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "project_id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "order" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "scenes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "shots" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "scene_id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "shot_number" INTEGER NOT NULL,
    "scene_graph" JSONB NOT NULL,
    "prompt" TEXT,
    "style_ref" UUID,
    "character_refs" UUID[],
    "audio_track_id" UUID,
    "duration_ms" INTEGER,
    "aspect_ratio" TEXT NOT NULL DEFAULT '16:9',
    "status" TEXT NOT NULL DEFAULT 'draft',
    "approved_by" UUID,
    "approved_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "shots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "characters" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "project_id" UUID,
    "owner_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "is_digital_twin" BOOLEAN NOT NULL DEFAULT false,
    "face_model_url" TEXT,
    "body_params" JSONB NOT NULL DEFAULT '{}',
    "hair_params" JSONB NOT NULL DEFAULT '{}',
    "wardrobe" JSONB NOT NULL DEFAULT '{}',
    "voice_id" TEXT,
    "style_mode" TEXT NOT NULL DEFAULT 'realistic',
    "facs_rig_url" TEXT,
    "gltf_url" TEXT,
    "consent_record" UUID,
    "rights_status" TEXT NOT NULL DEFAULT 'personal',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "characters_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "assets" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "project_id" UUID NOT NULL,
    "type" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "assets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "style_packs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "creator_id" UUID NOT NULL,
    "fingerprint" JSONB NOT NULL,
    "source_url" TEXT NOT NULL,
    "source_type" TEXT NOT NULL,
    "is_public" BOOLEAN NOT NULL DEFAULT false,
    "price" DOUBLE PRECISION,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "style_packs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "generation_jobs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "shot_id" UUID,
    "project_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "job_type" TEXT NOT NULL,
    "model_id" TEXT NOT NULL,
    "input_params" JSONB NOT NULL,
    "input_hash" TEXT,
    "tier" TEXT NOT NULL DEFAULT 'preview',
    "status" TEXT NOT NULL DEFAULT 'queued',
    "progress" INTEGER NOT NULL DEFAULT 0,
    "output_url" TEXT,
    "c2pa_manifest" TEXT,
    "watermark_id" TEXT,
    "quality_scores" JSONB,
    "cost_credits" DOUBLE PRECISION,
    "gpu_class" TEXT,
    "started_at" TIMESTAMPTZ,
    "completed_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_public" BOOLEAN NOT NULL DEFAULT false,
    "public_caption" TEXT,
    "public_likes" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "generation_jobs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audio_tracks" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "project_id" UUID NOT NULL,
    "type" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "duration" INTEGER NOT NULL,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audio_tracks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "consents" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "subject_id" UUID NOT NULL,
    "granted_by" UUID NOT NULL,
    "consent_type" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ,
    "revoked_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "consents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "moderation_logs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "job_id" UUID NOT NULL,
    "result" TEXT NOT NULL,
    "category" TEXT,
    "score" DOUBLE PRECISION,
    "details" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "moderation_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_trail" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "action" TEXT NOT NULL,
    "resource" TEXT NOT NULL,
    "resource_id" UUID NOT NULL,
    "details" JSONB NOT NULL DEFAULT '{}',
    "ip" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_trail_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "subscriptions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "stripe_id" TEXT NOT NULL,
    "tier" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "current_period_end" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "subscriptions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "usage_meters" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "period" TEXT NOT NULL,
    "credits_used" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "usage_meters_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notifications" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "body" TEXT,
    "action_url" TEXT,
    "is_read" BOOLEAN NOT NULL DEFAULT false,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "shot_reviews" (
    "id" TEXT NOT NULL,
    "shot_id" TEXT NOT NULL,
    "project_id" TEXT NOT NULL,
    "reviewer_name" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "comment" TEXT,
    "token" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "shot_reviews_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "publish_jobs" (
    "id" TEXT NOT NULL,
    "project_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "export_url" TEXT NOT NULL,
    "platform" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "scheduled_at" TIMESTAMPTZ NOT NULL,
    "published_at" TIMESTAMPTZ,
    "status" TEXT NOT NULL DEFAULT 'scheduled',
    "platform_id" TEXT,
    "error" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "publish_jobs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user_presences" (
    "user_id" TEXT NOT NULL,
    "org_id" TEXT,
    "current_page" TEXT,
    "status" TEXT NOT NULL DEFAULT 'offline',
    "last_seen" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "user_presences_pkey" PRIMARY KEY ("user_id")
);

-- CreateTable
CREATE TABLE "feedbacks" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "current_url" TEXT,
    "user_agent" TEXT,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "status" TEXT NOT NULL DEFAULT 'new',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "feedbacks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "changelog_views" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "viewed_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "changelog_views_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "referral_records" (
    "id" TEXT NOT NULL,
    "referrer_id" TEXT NOT NULL,
    "referee_id" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "credited_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "referral_records_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "feature_flags" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "rollout_pct" INTEGER NOT NULL DEFAULT 0,
    "allowlist" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "blocklist" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "description" TEXT,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "feature_flags_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "incidents" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "severity" TEXT NOT NULL,
    "services" TEXT[],
    "status" TEXT NOT NULL DEFAULT 'investigating',
    "resolved_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "incidents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "incident_updates" (
    "id" TEXT NOT NULL,
    "incident_id" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "incident_updates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "webhook_deliveries" (
    "id" TEXT NOT NULL,
    "webhook_id" TEXT NOT NULL,
    "event" TEXT NOT NULL,
    "request_body" TEXT NOT NULL,
    "request_headers" JSONB NOT NULL,
    "response_status" INTEGER,
    "response_body" TEXT,
    "duration_ms" INTEGER,
    "success" BOOLEAN NOT NULL DEFAULT false,
    "error" TEXT,
    "attempt_number" INTEGER NOT NULL DEFAULT 1,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "webhook_deliveries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "live_sessions" (
    "id" TEXT NOT NULL,
    "user_id" TEXT,
    "project_id" TEXT,
    "mode" TEXT,
    "avatar_id" TEXT,
    "status" TEXT NOT NULL DEFAULT 'offline',
    "destinations" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "started_at" TIMESTAMPTZ,
    "ended_at" TIMESTAMPTZ,
    "viewer_peak" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "live_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "branching_scenes" (
    "id" TEXT NOT NULL,
    "narrative_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "trigger_type" TEXT NOT NULL,
    "emotion" TEXT,
    "pose" TEXT,
    "position" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "branching_scenes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "piracy_matches" (
    "id" TEXT NOT NULL,
    "output_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "platform" TEXT NOT NULL,
    "match_url" TEXT NOT NULL,
    "match_strength" DOUBLE PRECISION NOT NULL,
    "watermark_found" BOOLEAN NOT NULL DEFAULT false,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "detected_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reviewed_at" TIMESTAMPTZ,
    "fingerprint_id" TEXT,
    "match_method" TEXT NOT NULL DEFAULT 'unknown',
    "hamming_distance" INTEGER,
    "watermark_id" TEXT,
    "evidence" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "piracy_matches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "dmca_notices" (
    "id" TEXT NOT NULL,
    "match_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "platform" TEXT NOT NULL DEFAULT 'unknown',
    "status" TEXT NOT NULL DEFAULT 'draft',
    "body" TEXT,
    "filed_at" TIMESTAMPTZ,
    "case_number" TEXT,
    "response_at" TIMESTAMPTZ,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "dmca_notices_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "c2pa_manifests" (
    "id" TEXT NOT NULL,
    "output_id" TEXT NOT NULL,
    "job_id" TEXT NOT NULL,
    "project_id" TEXT,
    "user_id_hash" TEXT,
    "asset_url" TEXT,
    "asset_path" TEXT,
    "asset_sha256" TEXT,
    "signed_asset_sha256" TEXT,
    "format" TEXT NOT NULL,
    "manifest_label" TEXT,
    "claim_generator" TEXT NOT NULL,
    "signature_alg" TEXT,
    "cert_serial_number" TEXT,
    "cert_issuer" TEXT,
    "timestamped_at" TIMESTAMPTZ,
    "signed" BOOLEAN NOT NULL DEFAULT false,
    "embedded" BOOLEAN NOT NULL DEFAULT false,
    "mode" TEXT NOT NULL DEFAULT 'degraded',
    "degraded_reason" TEXT,
    "manifest_json" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "c2pa_manifests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "watermarks" (
    "id" TEXT NOT NULL,
    "watermark_id" TEXT NOT NULL,
    "job_id" TEXT NOT NULL,
    "output_id" TEXT,
    "user_id" TEXT,
    "payload_hex" TEXT NOT NULL,
    "algorithm" TEXT NOT NULL DEFAULT 'dct-pair-v1',
    "strength" DOUBLE PRECISION NOT NULL DEFAULT 20,
    "seed" TEXT NOT NULL,
    "media_type" TEXT NOT NULL,
    "mode" TEXT NOT NULL DEFAULT 'embedded',
    "source_sha256" TEXT,
    "marked_sha256" TEXT,
    "output_url" TEXT,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "embedded_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "watermarks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "fingerprints" (
    "id" TEXT NOT NULL,
    "output_id" TEXT NOT NULL,
    "user_id" TEXT,
    "media_type" TEXT NOT NULL,
    "algorithm" TEXT NOT NULL DEFAULT 'phash-dct64',
    "phash" TEXT NOT NULL,
    "ahash" TEXT,
    "dhash" TEXT,
    "frame_hashes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "duration_ms" INTEGER,
    "width" INTEGER,
    "height" INTEGER,
    "source_sha256" TEXT,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "fingerprints_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "calendar_events" (
    "id" TEXT NOT NULL,
    "project_id" TEXT,
    "user_id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "start_date" TIMESTAMPTZ NOT NULL,
    "end_date" TIMESTAMPTZ NOT NULL,
    "owner_id" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "description" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "calendar_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "task_dependencies" (
    "id" TEXT NOT NULL,
    "from_task_id" TEXT NOT NULL,
    "to_task_id" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'blocks',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "task_dependencies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "live_recordings" (
    "id" TEXT NOT NULL,
    "session_id" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "duration_ms" INTEGER,
    "frames_rendered" INTEGER,
    "saved_at" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "live_recordings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "live_chat_messages" (
    "id" TEXT NOT NULL,
    "session_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "timestamp" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "live_chat_messages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "marketplace_items" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "price" DECIMAL(12,2) NOT NULL,
    "description" TEXT NOT NULL,
    "preview_url" TEXT NOT NULL,
    "creator_id" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "featured" BOOLEAN NOT NULL DEFAULT false,
    "category" TEXT NOT NULL,
    "purchase_count" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "marketplace_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "talent_profiles" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "skills" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "portfolio" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "rates" JSONB NOT NULL DEFAULT '{}',
    "availability" TEXT NOT NULL DEFAULT 'available',
    "average_rating" DECIMAL(3,2) NOT NULL DEFAULT 0,
    "review_count" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "talent_profiles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "talent_bookings" (
    "id" TEXT NOT NULL,
    "talent_id" TEXT NOT NULL,
    "project_id" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "dates" JSONB NOT NULL DEFAULT '{}',
    "rate" DECIMAL(12,2) NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "talent_bookings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "receipts" (
    "receipt_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "details" JSONB NOT NULL DEFAULT '{}',
    "status" TEXT NOT NULL DEFAULT 'confirmed',
    "project_id" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "receipts_pkey" PRIMARY KEY ("receipt_id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "users_referral_code_key" ON "users"("referral_code");

-- CreateIndex
CREATE UNIQUE INDEX "organizations_slug_key" ON "organizations"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "api_keys_key_hash_key" ON "api_keys"("key_hash");

-- CreateIndex
CREATE UNIQUE INDEX "projects_review_token_key" ON "projects"("review_token");

-- CreateIndex
CREATE UNIQUE INDEX "subscriptions_stripe_id_key" ON "subscriptions"("stripe_id");

-- CreateIndex
CREATE UNIQUE INDEX "usage_meters_user_id_period_key" ON "usage_meters"("user_id", "period");

-- CreateIndex
CREATE INDEX "notifications_user_id_is_read_idx" ON "notifications"("user_id", "is_read");

-- CreateIndex
CREATE INDEX "notifications_user_id_created_at_idx" ON "notifications"("user_id", "created_at");

-- CreateIndex
CREATE INDEX "shot_reviews_shot_id_idx" ON "shot_reviews"("shot_id");

-- CreateIndex
CREATE INDEX "shot_reviews_project_id_idx" ON "shot_reviews"("project_id");

-- CreateIndex
CREATE INDEX "feedbacks_type_status_idx" ON "feedbacks"("type", "status");

-- CreateIndex
CREATE UNIQUE INDEX "changelog_views_user_id_version_key" ON "changelog_views"("user_id", "version");

-- CreateIndex
CREATE UNIQUE INDEX "referral_records_referee_id_key" ON "referral_records"("referee_id");

-- CreateIndex
CREATE INDEX "referral_records_referrer_id_idx" ON "referral_records"("referrer_id");

-- CreateIndex
CREATE UNIQUE INDEX "feature_flags_key_key" ON "feature_flags"("key");

-- CreateIndex
CREATE INDEX "webhook_deliveries_webhook_id_created_at_idx" ON "webhook_deliveries"("webhook_id", "created_at");

-- CreateIndex
CREATE INDEX "live_sessions_user_id_idx" ON "live_sessions"("user_id");

-- CreateIndex
CREATE INDEX "live_sessions_project_id_idx" ON "live_sessions"("project_id");

-- CreateIndex
CREATE INDEX "branching_scenes_narrative_id_idx" ON "branching_scenes"("narrative_id");

-- CreateIndex
CREATE INDEX "piracy_matches_user_id_status_idx" ON "piracy_matches"("user_id", "status");

-- CreateIndex
CREATE INDEX "piracy_matches_fingerprint_id_idx" ON "piracy_matches"("fingerprint_id");

-- CreateIndex
CREATE INDEX "dmca_notices_match_id_idx" ON "dmca_notices"("match_id");

-- CreateIndex
CREATE UNIQUE INDEX "c2pa_manifests_output_id_key" ON "c2pa_manifests"("output_id");

-- CreateIndex
CREATE INDEX "c2pa_manifests_job_id_idx" ON "c2pa_manifests"("job_id");

-- CreateIndex
CREATE INDEX "c2pa_manifests_signed_asset_sha256_idx" ON "c2pa_manifests"("signed_asset_sha256");

-- CreateIndex
CREATE UNIQUE INDEX "watermarks_watermark_id_key" ON "watermarks"("watermark_id");

-- CreateIndex
CREATE INDEX "watermarks_job_id_idx" ON "watermarks"("job_id");

-- CreateIndex
CREATE INDEX "watermarks_payload_hex_idx" ON "watermarks"("payload_hex");

-- CreateIndex
CREATE INDEX "fingerprints_output_id_idx" ON "fingerprints"("output_id");

-- CreateIndex
CREATE INDEX "fingerprints_phash_idx" ON "fingerprints"("phash");

-- CreateIndex
CREATE INDEX "calendar_events_user_id_start_date_idx" ON "calendar_events"("user_id", "start_date");

-- CreateIndex
CREATE UNIQUE INDEX "task_dependencies_from_task_id_to_task_id_key" ON "task_dependencies"("from_task_id", "to_task_id");

-- CreateIndex
CREATE INDEX "live_recordings_session_id_idx" ON "live_recordings"("session_id");

-- CreateIndex
CREATE INDEX "live_chat_messages_session_id_timestamp_idx" ON "live_chat_messages"("session_id", "timestamp");

-- CreateIndex
CREATE INDEX "marketplace_items_creator_id_idx" ON "marketplace_items"("creator_id");

-- CreateIndex
CREATE INDEX "marketplace_items_status_featured_idx" ON "marketplace_items"("status", "featured");

-- CreateIndex
CREATE INDEX "talent_profiles_availability_idx" ON "talent_profiles"("availability");

-- CreateIndex
CREATE INDEX "talent_bookings_talent_id_idx" ON "talent_bookings"("talent_id");

-- CreateIndex
CREATE INDEX "talent_bookings_project_id_idx" ON "talent_bookings"("project_id");

-- CreateIndex
CREATE INDEX "receipts_user_id_created_at_idx" ON "receipts"("user_id", "created_at");

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teams" ADD CONSTRAINT "teams_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "api_keys" ADD CONSTRAINT "api_keys_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "projects" ADD CONSTRAINT "projects_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "projects" ADD CONSTRAINT "projects_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "scenes" ADD CONSTRAINT "scenes_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shots" ADD CONSTRAINT "shots_scene_id_fkey" FOREIGN KEY ("scene_id") REFERENCES "scenes"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shots" ADD CONSTRAINT "shots_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shots" ADD CONSTRAINT "shots_approved_by_fkey" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "characters" ADD CONSTRAINT "characters_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "generation_jobs" ADD CONSTRAINT "generation_jobs_shot_id_fkey" FOREIGN KEY ("shot_id") REFERENCES "shots"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "generation_jobs" ADD CONSTRAINT "generation_jobs_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "generation_jobs" ADD CONSTRAINT "generation_jobs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "incident_updates" ADD CONSTRAINT "incident_updates_incident_id_fkey" FOREIGN KEY ("incident_id") REFERENCES "incidents"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "piracy_matches" ADD CONSTRAINT "piracy_matches_fingerprint_id_fkey" FOREIGN KEY ("fingerprint_id") REFERENCES "fingerprints"("id") ON DELETE SET NULL ON UPDATE CASCADE;

