/**
 * Tests for the Avatar Studio client.
 *
 * Most of these guard honesty properties rather than plumbing: a procedural
 * result must not be recorded as a digital twin, a skipped stage must not be
 * reported as completed, and an absent identity score must stay absent rather
 * than becoming a plausible-looking number.
 */
import { describe, it, expect, vi } from 'vitest';

import {
  AvatarApiError,
  completedStepNames,
  describeCapability,
  fetchCapabilities,
  generateAvatar,
  identityScore,
  persistAvatarArtifacts,
  reconstructAndPersist,
  resolveAiBaseUrl,
  skippedSteps,
  type AvatarCapability,
  type AvatarJob,
} from './avatarApi';

const mockCapability: AvatarCapability = {
  requested_engine: 'mock',
  active_engine: 'mock',
  real_engine_available: false,
  torch_installed: false,
  gsplat_installed: false,
  cuda_available: false,
  cuda_device_count: 0,
  weights_present: false,
  missing: ['torch', 'gsplat', 'AVATAR_WEIGHTS_DIR'],
  notes: 'Procedural (mock) engine active.',
  identity_scoring_available: false,
  flame_fitting_available: false,
  mock_notice: 'Generated by the procedural CPU engine.',
};

const mockJob: AvatarJob = {
  job_id: 'job-1',
  engine: 'mock',
  requested_engine: 'mock',
  is_mock: true,
  mock_notice: 'Generated by the procedural CPU engine.',
  model_url: 'file:///artifacts/c1/job-1/avatar.glb',
  rig_url: 'file:///artifacts/c1/job-1/facs_rig.json',
  splat_url: 'file:///artifacts/c1/job-1/splats.ply',
  eye_animation_url: 'file:///artifacts/c1/job-1/eye_animation.json',
  steps_completed: [
    { step: 1, name: 'multi_view_alignment', description: '', status: 'completed' },
    { step: 2, name: 'volumetric_reconstruction', description: '', status: 'completed' },
    { step: 3, name: 'mesh_extraction', description: '', status: 'completed' },
    { step: 4, name: 'texture_baking', description: '', status: 'completed' },
    {
      step: 5,
      name: 'flame_fitting',
      description: '',
      status: 'skipped',
      reason: 'FLAME requires a licensed model file',
    },
    { step: 6, name: 'body_estimation', description: '', status: 'completed' },
    {
      step: 7,
      name: 'quality_validation',
      description: '',
      status: 'skipped',
      reason: 'No face-recognition model configured',
      metrics: { identity_score: null, identity_threshold: 0.92 },
    },
  ],
  steps_summary: { completed: 5, skipped: 2, failed: 0 },
  artifacts: {},
  skin: {},
  body_params: { estimated_stature_m: 1.72 },
  eye_statistics: { saccade_count: 30 },
  warnings: ['Generated by the procedural CPU engine.'],
};

function jsonResponse(body: unknown, status = 200): Response {
  return {
    ok: status >= 200 && status < 300,
    status,
    json: async () => body,
  } as unknown as Response;
}

/* ── Transport ───────────────────────────────────────────────────────────── */

describe('fetchCapabilities', () => {
  it('GETs the capability endpoint', async () => {
    const fetchImpl = vi.fn().mockResolvedValue(jsonResponse(mockCapability));

    const capability = await fetchCapabilities({
      aiBaseUrl: 'https://ai.test',
      fetchImpl: fetchImpl as unknown as typeof fetch,
    });

    expect(fetchImpl.mock.calls[0][0]).toBe('https://ai.test/ai/v1/avatar/capabilities');
    expect(capability.real_engine_available).toBe(false);
  });

  it('defaults the AI base URL', () => {
    expect(resolveAiBaseUrl()).toBe('http://localhost:8001');
  });

  it('strips trailing slashes', () => {
    expect(resolveAiBaseUrl({ aiBaseUrl: 'https://ai.test//' })).toBe('https://ai.test');
  });
});

describe('generateAvatar', () => {
  it('POSTs the request in the API\'s snake_case shape', async () => {
    const fetchImpl = vi.fn().mockResolvedValue(jsonResponse(mockJob, 201));

    await generateAvatar(
      {
        characterId: 'c1',
        photos: ['a.jpg', 'b.jpg'],
        styleMode: 'anime',
        skinTone: '#C68642',
      },
      { aiBaseUrl: 'https://ai.test', fetchImpl: fetchImpl as unknown as typeof fetch },
    );

    const [url, init] = fetchImpl.mock.calls[0];
    expect(url).toBe('https://ai.test/ai/v1/generate/avatar');
    expect(JSON.parse(init.body)).toEqual({
      character_id: 'c1',
      photos: ['a.jpg', 'b.jpg'],
      style_mode: 'anime',
      skin_tone: '#C68642',
      eye_clip_seconds: 10,
    });
  });

  it('surfaces the 503 raised when the real engine is unavailable', async () => {
    const fetchImpl = vi.fn().mockResolvedValue(
      jsonResponse({ detail: 'AVATAR_ENGINE=real requested but missing: torch' }, 503),
    );

    await expect(
      generateAvatar(
        { characterId: 'c1', photos: ['a.jpg'] },
        { fetchImpl: fetchImpl as unknown as typeof fetch },
      ),
    ).rejects.toThrow(/missing: torch/);
  });

  it('raises AvatarApiError with the status', async () => {
    const fetchImpl = vi.fn().mockResolvedValue(jsonResponse({ detail: 'nope' }, 422));

    await expect(
      generateAvatar(
        { characterId: 'c1', photos: [] },
        { fetchImpl: fetchImpl as unknown as typeof fetch },
      ),
    ).rejects.toBeInstanceOf(AvatarApiError);
  });
});

describe('persistAvatarArtifacts', () => {
  it('PUTs the produced URLs to the character record', async () => {
    const fetchImpl = vi.fn().mockResolvedValue(jsonResponse({ data: { id: 'c1' } }));

    await persistAvatarArtifacts('c1', mockJob, {
      platformBaseUrl: 'https://api.test',
      fetchImpl: fetchImpl as unknown as typeof fetch,
    });

    const [url, init] = fetchImpl.mock.calls[0];
    expect(url).toBe('https://api.test/api/v1/characters/c1/avatar');
    expect(init.method).toBe('PUT');
    expect(JSON.parse(init.body)).toMatchObject({
      gltfUrl: mockJob.model_url,
      facsRigUrl: mockJob.rig_url,
    });
  });

  it('does not mark a procedural result as a digital twin', async () => {
    const fetchImpl = vi.fn().mockResolvedValue(jsonResponse({ data: { id: 'c1' } }));

    await persistAvatarArtifacts('c1', mockJob, {
      fetchImpl: fetchImpl as unknown as typeof fetch,
    });

    expect(JSON.parse(fetchImpl.mock.calls[0][1].body).isDigitalTwin).toBe(false);
  });

  it('marks a real reconstruction as a digital twin', async () => {
    const fetchImpl = vi.fn().mockResolvedValue(jsonResponse({ data: { id: 'c1' } }));

    await persistAvatarArtifacts(
      'c1',
      { ...mockJob, is_mock: false, engine: 'real' },
      { fetchImpl: fetchImpl as unknown as typeof fetch },
    );

    expect(JSON.parse(fetchImpl.mock.calls[0][1].body).isDigitalTwin).toBe(true);
  });
});

describe('reconstructAndPersist', () => {
  it('runs the job then stores its artifacts', async () => {
    const fetchImpl = vi
      .fn()
      .mockResolvedValueOnce(jsonResponse(mockJob, 201))
      .mockResolvedValueOnce(jsonResponse({ data: { id: 'c1' } }));

    const job = await reconstructAndPersist(
      { characterId: 'c1', photos: ['a.jpg'] },
      { fetchImpl: fetchImpl as unknown as typeof fetch },
    );

    expect(job.job_id).toBe('job-1');
    expect(fetchImpl).toHaveBeenCalledTimes(2);
    expect(fetchImpl.mock.calls[1][1].method).toBe('PUT');
  });

  it('does not persist anything when the job fails', async () => {
    const fetchImpl = vi.fn().mockResolvedValue(jsonResponse({ detail: 'boom' }, 503));

    await expect(
      reconstructAndPersist(
        { characterId: 'c1', photos: ['a.jpg'] },
        { fetchImpl: fetchImpl as unknown as typeof fetch },
      ),
    ).rejects.toThrow();

    expect(fetchImpl).toHaveBeenCalledTimes(1);
  });
});

/* ── Presentation ────────────────────────────────────────────────────────── */

describe('describeCapability', () => {
  it('reports preview mode when the engine is procedural', () => {
    const described = describeCapability(mockCapability);
    expect(described.tone).toBe('mock');
    expect(described.headline).toMatch(/procedural/i);
  });

  it('reports ready when the real engine is available', () => {
    const described = describeCapability({
      ...mockCapability,
      real_engine_available: true,
      active_engine: 'real',
    });
    expect(described.tone).toBe('ready');
  });

  it('reports blocked when real was requested but cannot run', () => {
    const described = describeCapability({
      ...mockCapability,
      requested_engine: 'real',
    });
    expect(described.tone).toBe('blocked');
    expect(described.detail).toMatch(/torch/);
    expect(described.detail).toMatch(/fail rather than/i);
  });

  it('reports unknown before the probe returns', () => {
    expect(describeCapability(null).tone).toBe('unknown');
  });
});

describe('step reporting', () => {
  it('lists only the stages that actually ran', () => {
    expect(completedStepNames(mockJob)).toEqual([
      'multi_view_alignment',
      'volumetric_reconstruction',
      'mesh_extraction',
      'texture_baking',
      'body_estimation',
    ]);
  });

  it('does not report a skipped stage as completed', () => {
    expect(completedStepNames(mockJob)).not.toContain('flame_fitting');
    expect(completedStepNames(mockJob)).not.toContain('quality_validation');
  });

  it('lists skipped stages with their reasons', () => {
    const skipped = skippedSteps(mockJob);
    expect(skipped).toHaveLength(2);
    expect(skipped[0]).toEqual({
      name: 'flame_fitting',
      reason: 'FLAME requires a licensed model file',
    });
  });

  it('is empty before a job has run', () => {
    expect(completedStepNames(null)).toEqual([]);
    expect(skippedSteps(null)).toEqual([]);
  });
});

describe('identityScore', () => {
  it('is null when no identity check ran', () => {
    expect(identityScore(mockJob)).toBeNull();
  });

  it('is null before a job has run', () => {
    expect(identityScore(null)).toBeNull();
  });

  it('returns the score when one was computed', () => {
    const scored: AvatarJob = {
      ...mockJob,
      steps_completed: mockJob.steps_completed.map((step) =>
        step.name === 'quality_validation'
          ? { ...step, status: 'completed', metrics: { identity_score: 0.94 } }
          : step,
      ),
    };
    expect(identityScore(scored)).toBeCloseTo(0.94);
  });
});
