import type { Project, RenderJob, ActivityItem, DashboardStats, Character, CharacterStats } from './types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj_cyber_samurai',
    title: 'Cyber Samurai: Origin',
    description: 'A neo-Tokyo cyberpunk origin story featuring AI-generated environments and hand-directed character animation.',
    status: 'generating',
    projectType: 'cartoon',
    thumbnailGradient: 'linear-gradient(135deg, #0f0a2e, #1a0a3e, #0d1a3e)',
    totalShots: 24,
    approvedShots: 14,
    durationSeconds: 185,
    teamMembers: [
      { id: 'u1', name: 'Alice Chen', initials: 'AC', avatarColor: '#7c3aed' },
      { id: 'u2', name: 'Bob Martinez', initials: 'BM', avatarColor: '#06b6d4' },
      { id: 'u3', name: 'Carol Nakamura', initials: 'CN', avatarColor: '#f59e0b' },
    ],
    creditsCost: 340,
    updatedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: 'proj_last_garden',
    title: 'The Last Garden',
    description: 'A meditative short film about the final botanical garden on Earth, told through watercolor-style AI animation.',
    status: 'review',
    projectType: 'animation',
    thumbnailGradient: 'linear-gradient(135deg, #0a1f0a, #0d2b0d, #0a1a10)',
    totalShots: 16,
    approvedShots: 12,
    durationSeconds: 125,
    teamMembers: [
      { id: 'u1', name: 'Alice Chen', initials: 'AC', avatarColor: '#7c3aed' },
      { id: 'u4', name: 'Dave Okafor', initials: 'DO', avatarColor: '#ef4444' },
    ],
    creditsCost: 210,
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
  },
  {
    id: 'proj_echoes',
    title: 'Echoes of Tomorrow',
    description: 'Sci-fi anthology series exploring parallel timelines through mixed media AI generation.',
    status: 'draft',
    projectType: 'mixed',
    thumbnailGradient: 'linear-gradient(135deg, #0a1a2e, #1a0a2e, #0a2e1a)',
    totalShots: 0,
    approvedShots: 0,
    teamMembers: [
      { id: 'u1', name: 'Alice Chen', initials: 'AC', avatarColor: '#7c3aed' },
    ],
    creditsCost: 0,
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

export const MOCK_JOBS: RenderJob[] = [
  {
    id: 'job_1',
    projectId: 'proj_cyber_samurai',
    projectTitle: 'Cyber Samurai: Origin',
    shotNumber: 15,
    status: 'running',
    progress: 78,
    estimatedSecondsRemaining: 42,
    tier: 'standard',
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'job_2',
    projectId: 'proj_cyber_samurai',
    projectTitle: 'Cyber Samurai: Origin',
    shotNumber: 16,
    status: 'running',
    progress: 12,
    estimatedSecondsRemaining: 180,
    tier: 'preview',
    createdAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
  },
  {
    id: 'job_3',
    projectId: 'proj_last_garden',
    projectTitle: 'The Last Garden',
    shotNumber: 13,
    status: 'queued',
    progress: 0,
    tier: 'final',
    createdAt: new Date(Date.now() - 1000 * 30).toISOString(),
  },
];

export const MOCK_ACTIVITY: ActivityItem[] = [
  {
    id: 'act_1',
    type: 'approval',
    projectId: 'proj_cyber_samurai',
    projectTitle: 'Cyber Samurai: Origin',
    description: 'Shot 14 approved in Cyber Samurai: Origin',
    userId: 'u1',
    userInitials: 'AC',
    dotColor: '#6ee7b7',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'act_2',
    type: 'generation',
    projectId: 'proj_last_garden',
    projectTitle: 'The Last Garden',
    description: 'Generation complete — Shot 12 of The Last Garden',
    userId: 'u4',
    userInitials: 'DO',
    dotColor: '#fbbf24',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'act_3',
    type: 'share',
    projectId: 'proj_last_garden',
    projectTitle: 'The Last Garden',
    description: 'Review link shared for The Last Garden',
    userId: 'u1',
    userInitials: 'AC',
    dotColor: '#93c5fd',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'act_4',
    type: 'marketplace',
    projectTitle: 'Watercolor Dream',
    description: 'Style pack Watercolor Dream cloned from marketplace',
    userId: 'u1',
    userInitials: 'AC',
    dotColor: '#c4b5fd',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
];

export const MOCK_STATS: DashboardStats = {
  totalProjects: 3,
  totalShots: 40,
  approvedShots: 26,
  creditsUsed: 620,
  creditsTotal: 1000,
  activeRenderJobs: 2,
};

export const MOCK_CHARACTERS: Character[] = [
  {
    id: 'char_kai', name: 'Kai Tanaka', description: 'Cyberpunk samurai from Neo-Tokyo',
    styleMode: 'anime', status: 'active', isDigitalTwin: false, sourcePhotos: [],
    projectIds: ['proj_cyber_samurai'], driftScore: 92, avatarColor: '#7c3aed',
    shotCount: 12, rightsScope: undefined, createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'char_luna', name: 'Luna Evergreen', description: 'Guardian of the last garden on Earth',
    styleMode: 'cartoon', status: 'active', isDigitalTwin: true, sourcePhotos: ['/photos/luna1.jpg'],
    voiceId: 'voice_1', voiceName: 'Serene Female', projectIds: ['proj_last_garden'],
    driftScore: 78, avatarColor: '#10b981', shotCount: 8, rightsScope: 'commercial',
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'char_echo', name: 'Dr. Echo', description: 'Time scientist exploring parallel timelines',
    styleMode: 'realistic', status: 'draft', isDigitalTwin: false, sourcePhotos: [],
    projectIds: ['proj_echoes'], driftScore: undefined, avatarColor: '#f59e0b',
    shotCount: 0, createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'char_pixel', name: 'Pixel', description: 'Adorable robot companion with a heart of gold',
    styleMode: 'pixel', status: 'active', isDigitalTwin: false, sourcePhotos: [],
    projectIds: ['proj_cyber_samurai', 'proj_echoes'], driftScore: 85, avatarColor: '#ec4899',
    shotCount: 6, createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: 'char_maya', name: 'Maya Torres', description: 'Street artist turned digital activist',
    styleMode: 'cel-shaded', status: 'active', isDigitalTwin: true, sourcePhotos: ['/photos/maya1.jpg', '/photos/maya2.jpg'],
    voiceId: 'voice_2', voiceName: 'Bold Female', projectIds: ['proj_cyber_samurai'],
    driftScore: 65, avatarColor: '#06b6d4', shotCount: 4, rightsScope: 'personal',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 18000000).toISOString(),
  },
];

export const MOCK_CHARACTER_STATS: CharacterStats = {
  total: 5, activeInProjects: 4, digitalTwins: 2, voicesPaired: 2,
};
