import type { Project, RenderJob, ActivityItem, DashboardStats } from './types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj_cyber_samurai',
    title: 'Cyber Samurai: Origin',
    description: 'A neo-Tokyo cyberpunk origin story featuring AI-generated environments and hand-directed character animation.',
    status: 'generating',
    projectType: 'cartoon',
    thumbnailGradient: 'linear-gradient(135deg, #0f0a2e, #1a0a3e, #0d1a3e)',
    totalShots: 24,
    approvedShots: 14,
    durationSeconds: 185,
    teamMembers: [
      { id: 'u1', name: 'Alice Chen', initials: 'AC', avatarColor: '#7c3aed' },
      { id: 'u2', name: 'Bob Martinez', initials: 'BM', avatarColor: '#06b6d4' },
      { id: 'u3', name: 'Carol Nakamura', initials: 'CN', avatarColor: '#f59e0b' },
    ],
    creditsCost: 340,
    updatedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: 'proj_last_garden',
    title: 'The Last Garden',
    description: 'A meditative short film about the final botanical garden on Earth, told through watercolor-style AI animation.',
    status: 'review',
    projectType: 'animation',
    thumbnailGradient: 'linear-gradient(135deg, #0a1f0a, #0d2b0d, #0a1a10)',
    totalShots: 16,
    approvedShots: 12,
    durationSeconds: 125,
    teamMembers: [
      { id: 'u1', name: 'Alice Chen', initials: 'AC', avatarColor: '#7c3aed' },
      { id: 'u4', name: 'Dave Okafor', initials: 'DO', avatarColor: '#ef4444' },
    ],
    creditsCost: 210,
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
  },
  {
    id: 'proj_echoes',
    title: 'Echoes of Tomorrow',
    description: 'Sci-fi anthology series exploring parallel timelines through mixed media AI generation.',
    status: 'draft',
    projectType: 'mixed',
    thumbnailGradient: 'linear-gradient(135deg, #0a1a2e, #1a0a2e, #0a2e1a)',
    totalShots: 0,
    approvedShots: 0,
    teamMembers: [
      { id: 'u1', name: 'Alice Chen', initials: 'AC', avatarColor: '#7c3aed' },
    ],
    creditsCost: 0,
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

export const MOCK_JOBS: RenderJob[] = [
  {
    id: 'job_1',
    projectId: 'proj_cyber_samurai',
    projectTitle: 'Cyber Samurai: Origin',
    shotNumber: 15,
    status: 'running',
    progress: 78,
    estimatedSecondsRemaining: 42,
    tier: 'standard',
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'job_2',
    projectId: 'proj_cyber_samurai',
    projectTitle: 'Cyber Samurai: Origin',
    shotNumber: 16,
    status: 'running',
    progress: 12,
    estimatedSecondsRemaining: 180,
    tier: 'preview',
    createdAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
  },
  {
    id: 'job_3',
    projectId: 'proj_last_garden',
    projectTitle: 'The Last Garden',
    shotNumber: 13,
    status: 'queued',
    progress: 0,
    tier: 'final',
    createdAt: new Date(Date.now() - 1000 * 30).toISOString(),
  },
];

export const MOCK_ACTIVITY: ActivityItem[] = [
  {
    id: 'act_1',
    type: 'approval',
    projectId: 'proj_cyber_samurai',
    projectTitle: 'Cyber Samurai: Origin',
    description: 'Shot 14 approved in Cyber Samurai: Origin',
    userId: 'u1',
    userInitials: 'AC',
    dotColor: '#6ee7b7',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'act_2',
    type: 'generation',
    projectId: 'proj_last_garden',
    projectTitle: 'The Last Garden',
    description: 'Generation complete — Shot 12 of The Last Garden',
    userId: 'u4',
    userInitials: 'DO',
    dotColor: '#fbbf24',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'act_3',
    type: 'share',
    projectId: 'proj_last_garden',
    projectTitle: 'The Last Garden',
    description: 'Review link shared for The Last Garden',
    userId: 'u1',
    userInitials: 'AC',
    dotColor: '#93c5fd',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'act_4',
    type: 'marketplace',
    projectTitle: 'Watercolor Dream',
    description: 'Style pack Watercolor Dream cloned from marketplace',
    userId: 'u1',
    userInitials: 'AC',
    dotColor: '#c4b5fd',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
];

export const MOCK_STATS: DashboardStats = {
  totalProjects: 3,
  totalShots: 40,
  approvedShots: 26,
  creditsUsed: 620,
  creditsTotal: 1000,
  activeRenderJobs: 2,
};
